// Generated by ReScript, PLEASE EDIT WITH CARE


function case1(color) {
  return "\n:doodle {\n    @grid: 5x5 / 250px;\n    background-color: " + color + ";\n    border-radius: 4px;\n}\ntransition: .5s ease all;\n@even {\n    transform: rotate(@p(90deg, 270deg));\n}\n@odd {\n    transform: rotate(@p(0deg, 180deg));\n}\n::before,\n::after {\n    content: \"\";\n    position: absolute;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    background-image: @m(2, linear-gradient(\n    calc(90deg * @n()),\n    transparent 10%,\n    #fff 10%,\n    #fff calc(10% + 2px),\n    " + color + " calc(10% + 2px),\n    " + color + " 20%,\n    #fff 20%,\n    #fff calc(20% + 2px),\n    " + color + " calc(20% + 2px),\n    " + color + " 30%,\n    #fff 30%,\n    #fff calc(30% + 2px),\n    " + color + " calc(30% + 2px),\n    " + color + " 40%,\n    #fff 40%,\n    #fff calc(40% + 2px),\n    transparent calc(40% + 2px)\n    ));\n    clip-path: polygon(0 0, 100% 0 ,0 100%);\n}\n::after {\n    transform: rotate(180deg);\n}\n";
}

var case2 = "\n:doodle {\n@grid: 10x10 / 500px;\nbackground-color: #3e3d3d;\nborder-radius: 4px;\noverflow: hidden;\n}\n:container {\nleft: -25%;\ntransform-origin: 50% 0;\ntransform: scale(1.8);\n}\n::before {\ncontent: \"\";\nposition: absolute;\ntop: 0;\nright: 0;\nbottom: 0;\nleft: 0;\nmargin: auto;\nwidth: 10%;\nheight: 10%;\nbackground-color: #fff;\nborder-radius: 100%;\nbox-shadow: 0 0 0 2.2px #3e3d3d, 0 0 0 calc(2.2px * 2) #fff, 0 0 0 calc(2.2px * 3) #3e3d3d, 0 0 0 calc(2.2px * 4) #fff, 0 0 0 calc(2.2px * 5) #3e3d3d, 0 0 0 calc(2.2px * 6) #fff;\n}\n@row(even) {\ntransform: scale(1.8) translate3d(28%, calc(-40% * (@row() - 1)), 0);\n}\n@row(odd) {\ntransform: scale(1.8) translate3d(0, calc(-40% * (@row() - 1)), 0);\n}\n";

var case3 = "\n:doodle {\n    @grid: 18x1 / 250px;\n    background-color: #527b75;\n    border-radius: 4px;\n    font-size: 14px;\n    overflow: hidden;\n}\n@place-cell: center;\nwidth: 100%;\nheight: 100%;\n::before {\n    content: \"\";\n    position: absolute;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    background:\n    radial-gradient(1.15em 1.5714275em at 1.95em, rgba(255, 255, 255, 0) 47%, rgba(255, 255, 255, .9) 47%, rgba(255, 255, 255, .9) 60%, rgba(255, 255, 255, 0) 60%) calc(50% - .725em) 0,\n    radial-gradient(1.15em 1.5714275em at -0.47em, rgba(255, 255, 255, 0) 47%, rgba(255, 255, 255, .9) 47%, rgba(255, 255, 255, .9) 60%, rgba(255, 255, 255, 0) 60%) calc(50% + .725em) 1.2em;\n    background-size: 1.5em 2.4em, 1.5em 2.4em;\n    background-repeat: repeat-y;\n}\n@nth(1, 2, 3, 4, 5, 6, 7, 8, 9) {\n    ::before {\n    transform: scale(2.3) rotate(45deg);\n    }\n}\n@nth(10, 11, 12, 13, 14, 15, 16, 17, 18) {\n    ::before {\n    transform: scale(2.3) rotate(-45deg);\n    }\n}\n@nth(2, 10) {\n    transform: translateX(calc(-22% * 1));\n}\n@nth(3, 11) {\n    transform: translateX(calc(-22% * 2));\n}\n@nth(4, 12) {\n    transform: translateX(calc(-22% * 3));\n}\n@nth(5, 13) {\n    transform: translateX(calc(-22% * 4));\n}\n@nth(6, 14) {\n    transform: translateX(calc(22% * 1));\n}\n@nth(7, 15) {\n    transform: translateX(calc(22% * 2));\n}\n@nth(8, 16) {\n    transform: translateX(calc(22% * 3));\n}\n@nth(9, 17) {\n    transform: translateX(calc(22% * 4));\n}\n";

export {
  case1 ,
  case2 ,
  case3 ,
}
/* No side effect */
